In [ ]:
import numpy as np
np.__version__

In [ ]:
np.show_config()

In [ ]:
arr = np.zeros(10)
print(arr)
print(arr.size)
print(arr.itemsize)
# find the memory size of any array
print(arr.size*arr.itemsize)

In [ ]:
# 5.How to get the documentation of the numpy add function from the command line
# np.info

In [ ]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

In [ ]:
arr = np.arange(10, 50)
print(arr)
arr = arr[::-1]
print(arr)

In [ ]:
arr = np.arange(0,9)
print(arr)
arr = np.reshape(arr, (3,3))
print(arr)

In [ ]:
arr = [1,2,0,0,4,0]
print(np.nonzero(arr))

In [ ]:
arr = np.eye(3)
print(arr)

In [ ]:
# Create a 3x3x3 array with random values
arr = np.random.random((3,3,3))
print(arr)

In [ ]:
arr = np.random.random((10, 10))
print(arr)
print(arr.max())
print(arr.min())

In [ ]:
arr = np.random.random((30,))
print(arr)
print(arr.mean())

In [ ]:
# Create a 2d array with 1 on the border and 0 inside
arr = np.ones((5,5))
print(arr)
arr[1:-1, 1:-1] = 0
print(arr)

In [ ]:
# How to add a border (filled with 0's) around an existing array
arr = np.ones((5,5), dtype=int)
print(arr)
arr = np.pad(arr, 1, 'constant',constant_values = (0) )
print(arr)

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


In [ ]:
arr = np.zeros((5,5), dtype = int)
print(arr)
arr = np.diag([1,2,3,4], -1)
print(arr)

In [ ]:
arr = np.ones((8,8), dtype = int)
arr[::2, ::2] = 0
arr[1::2, 1::2] = 0
print(arr)

In [ ]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
print(np.unravel_index(99, (6,7,8)))

In [ ]:
# Create a checkerboard 8x8 matrix using the tile function
arr = np.eye(2, dtype=int)
print(arr)
arr = np.tile(arr, (4,4))
print(arr)

In [ ]:
# Normalize a 5x5 random matrix
arr = np.random.random((5,5))
print(arr)
e = np.std(arr)
print(e)
arr = (arr - arr.mean()) / e
print(arr)

In [ ]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])

In [ ]:
a = np.random.random((5,3))
print(a)
b = np.random.random((3,2))
print(b)
print(a.dot(b))

In [ ]:
arr = np.arange(10)
arr[(3<arr) & (arr<8)] *= -1
print(arr)

In [ ]:
# What is the output of the following script? 
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
# Consider an integer vector Z, which of these expressions are legal?
Z = np.arange(5)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z<Z)

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

In [ ]:
# How to round away from zero a float array
arr = np.random.uniform(-5,5,10)
print(arr)
arr = np.abs(arr)
# arr = np.copysign(arr, 1)
print(arr)
arr = np.ceil(arr)
print(arr)

# print(np.copysign(np.ceil(np.abs(arr)), arr))
# More readable but less efficient
# print(np.where(arr>0, np.ceil(arr), np.floor(arr)))


In [ ]:
# How to find common values between two arrays
a = np.random.randint(0, 10, 5)
print(a)
b = np.random.randint(0, 10, 10)
print(b)
print(intersect1d(a,b))

In [ ]:
# How to ignore all numpy warnings (not recommended)
defaults = np.seterr(divide="ignore")
a = np.ones(1) / 0
print(a)
_ = np.seterr(**defaults)
print(a)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
print(np.datetime64('2021-08-29') - np.timedelta64(1,'D'))
print(np.datetime64('2021-08-29'))
print(np.datetime64('2021-08-29') + np.timedelta64(1,'D'))

In [ ]:
print(np.arange('2016-07','2016-08', dtype = 'datetime64[D]'))

In [ ]:
a = np.ones(3)
b = np.ones(3) * 2
np.add(a,b,out=b)
np.negative(a, out=a)
np.divide(a,2, out=a)
np.multiply(a,b, out=b)
print(b)

In [ ]:
arr = np.random.uniform(0,10,10)
print(arr)
print(arr-arr%1)
print(np.floor(arr))
print(arr.astype(int)*1.)
print(np.trunc(arr))

In [ ]:
print(np.tile(np.arange(5), (5,1)))

In [ ]:
iterable = (x*x for x in range(10))
arr = np.fromiter(iterable, float)
print(arr)
# def generate():
#     for x in range(10):
#         yield x
# Z = np.fromiter(generate(),dtype=float,count=-1)
# print(Z)

In [ ]:
arr = np.linspace(0, 1, num=10, endpoint = False)[1:]
print(arr)

In [ ]:
arr = np.random.randint(0,10, 10)
arr.sort()
print(arr)

In [ ]:
arr = np.arange(10)
print(arr)
sum = np.add.reduce(arr)
print(sum)

In [ ]:
arr1 = np.array([1, 2])
arr2 = np.array([1, 2])
print(np.array_equal(arr1, arr2))
print(np.allclose(arr1, arr2))

In [ ]:
arr1 = np.array( [1, 2])
arr1.flags.writeable = False
# arr1[1] = 2

In [ ]:
z = np.random.random((10, 2))
print (z)
x = z[:,0]
print (x)
y = z[:, 1]
r = np.sqrt(x**2+y**2)
anpha = np.arctan2(y,x)
print(r)
print(anpha)

In [ ]:
arr = np.arange(10)
arr[np.argmax(arr)] = 0
print(arr)

In [ ]:
arr = np.zeros((5,5), dtype=[('x', float),('y', float)])
print(arr)
x = np.linspace(0,1,5)
y = np.linspace(0,1,5)
arr['x'], arr['y'] = np.meshgrid(x,y)
print(arr)

# Z = np.zeros((5,5), [('x',float),('y',float)])
# Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
#                              np.linspace(0,1,5))
# print(Z)


In [ ]:
x = np.random.randint(0,10,5)
y = x + 1.1
print(x,y)
c = 1.0/np.subtract.outer(x,y)
print(c)
print(np.linalg.det(c))

[9 5 2 0 2] [10.1  6.1  3.1  1.1  3.1]
[[-0.90909091  0.34482759  0.16949153  0.12658228  0.16949153]
 [-0.19607843 -0.90909091  0.52631579  0.25641026  0.52631579]
 [-0.12345679 -0.24390244 -0.90909091  1.11111111 -0.90909091]
 [-0.0990099  -0.16393443 -0.32258065 -0.90909091 -0.32258065]
 [-0.12345679 -0.24390244 -0.90909091  1.11111111 -0.90909091]]
-1.486254927924002e-16


In [ ]:
arr1 = [np.int8, np.int16, np.int32, np.int64]
for dtype in arr1 :
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
arr2 = [np.float16, np.float32, np.float64, np.float128]
for dtype in arr2:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

In [ ]:
np.set_printoptions(threshold=float("inf"))
arr = np.arange(1000)
print(arr)
# np.set_printoptions(threshold=float("inf"))
# Z = np.zeros((40,40))
# print(Z)

In [ ]:
# How to find the closest value (to a given scalar) in a vector
arr = np.arange(10)
print(arr)
x = np.random.uniform(0,10)
print(x)
print(arr[np.argmin(np.abs(arr-x))])

In [ ]:
# Create a structured array representing a position (x,y) and a color (r,g,b)
a = np.zeros(5,dtype=[('position',[('x', float), ('y', float)]),
                                  ('color', [('r', float), ('g', float), ('b', float)])])
print(a)

In [ ]:
# Consider a random vector with shape (100,2) representing coordinates, find point by point distances
arr = np.random.random((10,2))
print(arr)
x,y = np.atleast_2d(arr[:,0], arr[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

In [ ]:
# How to convert a float (32 bits) array into an integer (32 bits) in place
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
print(Y)
Y[:] = Z
print(Y)

[ 1.2806298 61.70064    0.6745638 13.778466  13.773373  61.91341
 33.376842  29.068396  65.886765  29.173815 ]
[1067707309 1115082101 1059893303 1096578201 1096572860 1115137877
 1107657187 1105759251 1115932166 1105814521]
[ 1 61  0 13 13 61 33 29 65 29]


In [ ]:
# How to read the following file
from io import StringIO
s = """1, 2, 3, 4, 5

        6,  ,  , 7, 8

        ,  , 9,10,11"""
Z = np.genfromtxt(StringIO(s), delimiter=",", dtype=np.int)
print(Z)

In [ ]:
# What is the equivalent of enumerate for numpy arrays
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)
for index in np.ndindex(a.shape):
    print(index, a[index])

In [ ]:
# Generate a generic 2D Gaussian-like array
# (1 / (σ * sqrt(2π))) * exp(-(x - μ)**2 / 2σ**2)
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

In [ ]:
# How to randomly place p elements in a 2D array
arr = np.zeros((5,5))
index = np.random.choice(range(5*5), 5)
np.put(arr,index, 3)
print(arr)

In [ ]:
# Subtract the mean of each row of a matrix
a = np.random.randn(3,3)
print(a)
a = a - a.mean(axis=1, keepdims=True)
print(a)

In [ ]:
# How to sort an array by the nth column
arr = np.random.randint(0,10,(3,3))
print(arr)
index = np.argsort(arr[:,0])
print(index)
print(arr[index])

In [ ]:
# How to tell if a given 2D array has null columns
arr = np.array([[0,1,2],[0,2,0],[0,3,4]])
print(arr)
print(np.any(arr, axis=0))
# print((~Z.any(axis=0)).any())


In [ ]:
# Find the nearest value from a given value in an array 
arr = np.arange(10)
print(arr)
x = np.random.uniform(0,10)
print(x)
m = arr.flat[np.abs(arr - x).argmin()]
print(m)

In [ ]:
# Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator
a = np.random.randint(0, 10, (1,3))
b = np.random.randint(0, 10, (3,1))
print(a)
print(b)
sum = []
for i in np.nditer(a.T):
    x = []
    for j in np.nditer(b):
        x.append(i + j)
    sum.append(x)   
print(np.array(sum))

In [ ]:
# Create an array class that has a name attribute

class NamedArray(np.ndarray):
   def __new__(cls, array, name="No Name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [ ]:
Z  = np.arange(10)
I = np.random.randint(0,len(Z),10)
print (I)
np.add.at(Z, I, 1)
print(Z)

[5 2 6 1 1 8 1 1 5 3]
[0 5 3 4 4 7 7 7 9 9]


In [ ]:
# How to accumulate elements of a vector (X) to an array (F) based on an index list (I)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
# F= 0 1 2 3 ....9
# 0=0 1=1+6
F = np.bincount(I,X) 
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
#  Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint32)
new = np.dot(I.astype(np.uint32), [1, 256, 256*256])
print( len(np.unique(new)))

In [ ]:
# Considering a four dimensions array, how to get sum over the last two axis at once
arr = np.random.randint(0,10,(2,2,2,2))
print(arr)
print(arr.sum(axis=(-2,-1)))

In [ ]:
# Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


In [ ]:
a = np.arange(15).reshape(3, 5)
b = np.arange(15).reshape(5, 3)
print(np.diag(np.dot(a,b)))

[ 90 275 510]


In [ ]:
Z = np.array([1,2,3,4,5])
Z0 = np.zeros(len(Z) + (len(Z)-1)*3)
Z0[::4] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
A = np.arange(25).reshape(5,5)
print (A)
A[[0,1]] = A[[1,0]]
# A[[0]], A[[1]] = A[[1]], A[[0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# faces = np.random.randint(0,100,(10,3))
# F = np.roll(faces.repeat(2,axis=1),-1,axis=1) 
# # axis = 1 la dich cot, 0 la dich hang
# print (F)
# F = F.reshape(len(F)*3,2)
# F = np.sort(F,axis=1)
# G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
# G = np.unique(G)
# print(G)

In [ ]:
# Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C
C = np.bincount([1,1,2,3,4,4,6])
print (C)
print (np.arange(len(C)))
A = np.repeat(np.arange(len(C)), C)
print(A)

In [ ]:
# 75.How to compute averages using a sliding window over an array
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    print (ret)
    print (ret[n:])
    print (ret[:-n])
    ret[n:] = ret[n:] - ret[:-n]
    print (ret)
    return ret // n
Z = np.arange(10)
print(Z)
print(moving_average(Z, n=3))

In [ ]:
# Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
def rolling(a, n):
    return np.lib.stride_tricks.as_strided(a, (a.size - n + 1, n), (a.itemsize, a.itemsize))
rolling(np.arange(10), 4)


In [ ]:
# How to negate a boolean, or to change the sign of a float inplace
a = np.array(np.arange(2) % 2 == 1)
print(a, np.logical_not(a))
b = np.arange(10).astype(float)
print(b, np.negative(b))

In [ ]:
#  Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])
P0 = np.random.rand(1, 2) * 10
P1 = np.random.rand(1, 2) * 10
C = np.array([1, 2])
print(P0, P1)
print(np.linalg.norm(P0 - P1, axis=1))
print(np.abs(np.cross(P0 - C, P1 - C, axis=1)))
np.abs(np.cross(P0 - C, P1 - C, axis=1)) / np.linalg.norm(P0 - P1, axis=1)

In [86]:
# Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])
P0 = np.random.rand(5, 2) * 10
P1 = np.random.rand(5, 2) * 10
P = np.random.rand(5, 2) * 10
# cross la tich vo huong
# linalg.norm 
for p in P:
    print ("Debug " , np.linalg.norm(P0 - P1, axis=1))
    print(np.abs(np.cross(P0 - p, P1 - p, axis=1)) / np.linalg.norm(P0 - P1, axis=1))

Debug  [6.28580065 5.09302473 3.90631885 4.82516737 1.27472836]
[8.20174795 3.37180382 7.65763668 5.6380089  2.14575428]
Debug  [6.28580065 5.09302473 3.90631885 4.82516737 1.27472836]
[1.34501093 7.50211858 1.04282968 4.89870367 5.21665126]
Debug  [6.28580065 5.09302473 3.90631885 4.82516737 1.27472836]
[1.40617586 1.52866764 0.61154524 0.39503629 5.00766073]
Debug  [6.28580065 5.09302473 3.90631885 4.82516737 1.27472836]
[0.29982981 4.14127213 0.74216499 2.62381292 5.8724341 ]
Debug  [6.28580065 5.09302473 3.90631885 4.82516737 1.27472836]
[4.23987363 2.22805823 4.37351449 0.70359067 0.17733915]


In [ ]:
# 80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)


In [ ]:
# Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]
A = np.arange(1, 15)
print(np.lib.stride_tricks.as_strided(A, (A.size - 3, 4), (A.itemsize, A.itemsize)))

In [ ]:
# 82 Compute a matrix rank

Z = np.random.uniform(0,1,(3,3))
print(Z)
U, S, V = np.linalg.svd(Z)
print('u = ',U,'\ns =', S,'\nv = ', V)
rank = np.sum(S > 1e-10)
print(rank)

[[0.82908985 0.06031462 0.45206248]
 [0.48131262 0.97442229 0.07349825]
 [0.14359868 0.84922413 0.56118997]]
u =  [[-0.40699029  0.91201482  0.05087116]
 [-0.67101943 -0.26072989 -0.69408418]
 [-0.61975143 -0.31662106  0.7180942 ]] 
s = [1.53316853 0.77962645 0.4245753 ] 
v =  [[-0.48878979 -0.78576594 -0.37902035]
 [ 0.75059444 -0.60020467  0.27633738]
 [-0.44462628 -0.14941968  0.88316546]]
3


In [ ]:
#  How to find the most frequent value in an array
a = np.random.randint(0,10,10)
print(a)
b = np.bincount(a)
print(b)
print(b.argmax())

In [ ]:
# Extract all the contiguous 3x3 blocks from a random 10x10 matrix
Z = np.random.randint(0,5,(10,10))
print('Z=', Z)
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, 3, 3), strides=Z.strides + Z.strides)
print(C)

In [ ]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
print(S)


In [ ]:
# Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
p, n = 3, 5
M = np.ones((p,n,n))
print(M)
V = np.ones((p,n,1))
print(V)
S = np.tensordot(M, V, ((0, 2), (0, 1)))
print(S)


In [ ]:
# Consider a 16x16 array, how to get the block-sum (block size is 4x4)
a = np.random.randint(0, 10, (16, 16))
print(a)
shape = (4,4)

sum_by_column = np.add.reduceat(a, np.arange(0, a.shape[0], shape[0]), axis=0)
s = np.add.reduceat( sum_by_column,
np.arange(0, a.shape[1], shape[1]), axis=1)
print(s)

In [ ]:
# How to implement the Game of Life using numpy arrays

In [ ]:
#  How to get the n largest values of an array 
Z = np.arange(1000)
np.random.shuffle(Z)
n = 5
print(Z[np.argsort(Z)[-n:]])

In [ ]:
# Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


In [ ]:
# How to create a record array from a regular array
x1=np.array([1, 2, 3, 4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1, 2, 3, 4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])
print(r)

In [ ]:
# Consider a large vector Z, compute Z to the power of 3 using 3 different methods 
Z = np.random.choice(100,10000)
print(Z)
print(np.power(Z,3))
print(Z**3)
print(Z*Z*Z)
print(np.einsum('i,i,i->i',Z,Z,Z))

In [ ]:
# Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B

# Don't understand ??? fuck 

# A = np.random.randint(0,5,(8,3))
# B = np.random.randint(0,5,(2,2))

# C = (A[..., np.newaxis, np.newaxis] == B)
# rows = np.where(C.any((3,1)).all(1))[0]
# print(rows)


In [ ]:

Z = np.random.randint(0,5,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 2 4]
 [3 3 0]
 [3 2 1]
 [1 2 1]
 [1 2 3]
 [3 1 4]
 [3 4 3]
 [2 0 0]
 [0 3 4]
 [1 1 3]]
[[3 3 0]
 [1 2 1]]


In [ ]:

I = np.array([0, 6, 2, 3, 15, 16, 32, 64, 128])
# shape(-1,1), -1 auto fit vs kich thuoc arr
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print (B)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
